// メニューの追加
function onOpen() {
  SpreadsheetApp.getUi()
      .createMenu('Optional menu')
      .addItem('Upload a CSV file generated by cbnews', 'csvDialog')
      .addToUi();
}

// ダイアログを表示
function csvDialog() {
  var html = HtmlService.createHtmlOutputFromFile('index');
  SpreadsheetApp.getUi().showModalDialog(html, 'Upload a CSV file generated by cbnews');
}

// アップロード処理
function uploadProcess(formObject) {
  var rowIndex = parseInt(formObject.rowNumber);
  var csvValues = Utilities.parseCsv(formObject.myFile.getDataAsString());
  var sheet = SpreadsheetApp.getActiveSheet();
  const mp = [1, 2, 3, 4, 5, 6];
  
  for(var i=0;i<6;i++) {
    var vals = [];
    for(var j=1;j<csvValues.length;j++) {
      vals.push([csvValues[j][i]]);
    }
    //Browser.msgBox("最終行取得", rowIndex + " " + mp[i] + " "+vals.length + " "+mp[i], Browser.Buttons.OK);
    sheet.getRange(rowIndex, mp[i], vals.length, 1).setValues(vals);
  }
  
}

/*
// アップロード処理
function uploadProcess(formObject) {
  var rowIndex = parseInt(formObject.rowNumber);
  var formBlob = formObject.myFile;
  var csvText = formBlob.getDataAsString();    
  var values = Utilities.parseCsv(csvText);
 // SpreadsheetApp.getActiveSheet().getRange(1, 1, values.length, values[0].length).setValues(values);
  var sheet = SpreadsheetApp.getActiveSheet();
  const mp = [1, 2, 3, 4, 5, 6];
  for(var i=0;i<6;i++) {
    // const lastRow = sheet.getRange(mp[i] + ':' + mp[i]).getValues().filter(String).length;
    var vals = [];
    for(var j=1;j<values.length;j++) {
      //sheet.getRange(mp[i] + (lastRow+j)).setValue(values[j][i]);
      //vals.push([values[j][i]]);
    }
    Browser.msgBox("最終行取得", (lastRow+1)+" "+mp[i] + " "+(lastRow+vals.length), Browser.Buttons.OK);
     //Browser.msgBox("doge", vals, Browser.Buttons.OK);
    //sheet.getRange(lastRow+1, mp[i], lastRow+vals.length, mp[i]).setValues([['doge']]);
    sheet.getRange(1, mp[i], 1, mp[i]).setValues([['doge']]);
  }
  
}
*/
